export {
  calendarBaseClasses,
  calendarContainerClasses,
  monthContainerClasses,
  selectedDateHeaderClasses,
  headerClasses,
  headerTitleClasses,
  headerNavClasses,
  headerTitleButtonClasses,
  headerNavButtonBaseClasses,
  headerNavButtonEnabledClasses,
  headerNavButtonDisabledClasses,
  gridClasses,
  weekdayClasses,
  dayBaseClasses,
  dayHoverClasses,
  daySelectedClasses,
  dayTodayClasses,
  dayOutsideClasses,
  dayDisabledClasses,
  dayInRangeClasses,
  dayWrapperInRangeClasses,
  dayWrapperRangeStartClasses,
  dayWrapperRangeEndClasses,
  viewContainerClasses,
  monthViewContainerClasses,
  monthGridClasses,
  monthItemClasses,
  monthItemActiveClasses,
  monthItemInactiveClasses,
  monthItemNextYearClasses,
  yearGridClasses,
  yearItemClasses,
  yearItemActiveClasses,
  yearItemInactiveClasses,
  yearItemNextDecadeClasses,
} from "./base";

export {
  sizeClasses,
  daySizeClasses,
  weekdaySizeClasses,
  containerPaddingClasses,
  gapClasses,
} from "./sizes";

import {
  calendarBaseClasses,
  calendarContainerClasses,
  monthContainerClasses,
  selectedDateHeaderClasses,
  headerClasses,
  headerTitleClasses,
  headerNavClasses,
  headerTitleButtonClasses,
  headerNavButtonBaseClasses,
  headerNavButtonEnabledClasses,
  headerNavButtonDisabledClasses,
  gridClasses,
  weekdayClasses,
  dayBaseClasses,
  dayHoverClasses,
  daySelectedClasses,
  dayTodayClasses,
  dayOutsideClasses,
  dayDisabledClasses,
  dayInRangeClasses,
  dayWrapperInRangeClasses,
  dayWrapperRangeStartClasses,
  dayWrapperRangeEndClasses,
  viewContainerClasses,
  monthViewContainerClasses,
  monthGridClasses,
  monthItemClasses,
  monthItemActiveClasses,
  monthItemInactiveClasses,
  monthItemNextYearClasses,
  yearGridClasses,
  yearItemClasses,
  yearItemActiveClasses,
  yearItemInactiveClasses,
  yearItemNextDecadeClasses,
} from "./base";

import {
  sizeClasses,
  daySizeClasses,
  weekdaySizeClasses,
  containerPaddingClasses,
  gapClasses,
} from "./sizes";

export const calendarStyles = {
  base: calendarBaseClasses,
  container: calendarContainerClasses,
  monthContainer: monthContainerClasses,
  selectedDateHeader: selectedDateHeaderClasses,
  header: headerClasses,
  headerTitle: headerTitleClasses,
  headerNav: headerNavClasses,
  headerTitleButton: headerTitleButtonClasses,
  headerNavButton: {
    base: headerNavButtonBaseClasses,
    enabled: headerNavButtonEnabledClasses,
    disabled: headerNavButtonDisabledClasses,
  },
  grid: gridClasses,
  weekday: weekdayClasses,
  day: {
    base: dayBaseClasses,
    hover: dayHoverClasses,
    selected: daySelectedClasses,
    today: dayTodayClasses,
    outside: dayOutsideClasses,
    disabled: dayDisabledClasses,
    inRange: dayInRangeClasses,
    wrapperInRange: dayWrapperInRangeClasses,
    wrapperRangeStart: dayWrapperRangeStartClasses,
    wrapperRangeEnd: dayWrapperRangeEndClasses,
  },
  viewContainer: viewContainerClasses,
  month: {
    container: monthViewContainerClasses,
    grid: monthGridClasses,
    item: monthItemClasses,
    active: monthItemActiveClasses,
    inactive: monthItemInactiveClasses,
    nextYear: monthItemNextYearClasses,
  },
  year: {
    grid: yearGridClasses,
    item: yearItemClasses,
    active: yearItemActiveClasses,
    inactive: yearItemInactiveClasses,
    nextDecade: yearItemNextDecadeClasses,
  },
  size: sizeClasses,
  daySize: daySizeClasses,
  weekdaySize: weekdaySizeClasses,
  containerPadding: containerPaddingClasses,
  gap: gapClasses,
} as const;
