export const ITEM_HEIGHT = 36;
export const SELECTION_PILL_HEIGHT = ITEM_HEIGHT;
export const CENTER_SPACER_HEIGHT = 90;
export const REPEAT_COUNT = 5;
export const MIDDLE_REPEAT_INDEX = Math.floor(REPEAT_COUNT / 2);

export const SCROLL_DEBOUNCE_MS = 120;
export const SCROLL_ADJUST_DELAY_SMOOTH = 250;
export const SCROLL_ADJUST_DELAY_INSTANT = 0;
export const PROGRAMMATIC_SCROLL_RELEASE_DELAY_MS = 80;

export const INSTANT_SCROLL_VALUE_DELTA_EXCLUSIVE = 10;

export const MOUSE_WHEEL_SCROLL_MULTIPLIER = 0.2;
export const MOUSE_WHEEL_LINE_HEIGHT = 16;
