import {
  sizeClasses,
  containerSizeClasses,
  clearButtonWrapperSizeClasses,
  floatingLabelOffsetSizeClasses,
  floatingLabelActiveTypographySizeClasses,
  nativePlaceholderTypographySizeClasses,
  nativeActiveWithoutTagsShiftSizeClasses,
} from "./sizes.ts";
import {
  clearButtonWrapperClasses,
  floatingLabelActiveClasses,
  inputBaseClasses,
  inputStateClasses,
  inputDisabledClasses,
  inputAdornmentClasses,
  inputAdornmentDisabledClasses,
  inputNativeClasses,
  inputNativeWithFloatingLabelClasses,
  inputNativeDisabledClasses,
  inputNativePlaceholderHiddenClasses,
  inputNativePlaceholderVisibleClasses,
  inputClearButtonClasses,
  nativeActiveWithoutTagsClasses,
  nativeTextClasses,
  tagsContainerClasses,
  tagsContainerWithTagsClasses,
  tagsContainerWithFloatingLabelClasses,
  wrapperClasses,
  wrapperEmptyClasses,
  wrapperWithTags,
} from "./base.ts";

export const inputTagStyles = {
  base: inputBaseClasses,
  state: inputStateClasses,
  disabled: inputDisabledClasses,
  adornment: inputAdornmentClasses,
  adornmentDisabled: inputAdornmentDisabledClasses,
  native: inputNativeClasses,
  nativeWithFloatingLabel: inputNativeWithFloatingLabelClasses,
  nativeDisabled: inputNativeDisabledClasses,
  nativePlaceholderHidden: inputNativePlaceholderHiddenClasses,
  nativePlaceholderVisible: inputNativePlaceholderVisibleClasses,
  clearButton: inputClearButtonClasses,
  size: sizeClasses,
  containerSize: containerSizeClasses,
  wrapper: wrapperClasses,
  wrapperEmpty: wrapperEmptyClasses,
  wrapperWithTags: wrapperWithTags,
  tagsContainer: tagsContainerClasses,
  tagsContainerWithTags: tagsContainerWithTagsClasses,
  tagsContainerWithFloatingLabel: tagsContainerWithFloatingLabelClasses,
  clearButtonWrapper: clearButtonWrapperClasses,
  clearButtonWrapperSize: clearButtonWrapperSizeClasses,
  floatingLabelOffsetSize: floatingLabelOffsetSizeClasses,
  floatingLabelActive: floatingLabelActiveClasses,
  floatingLabelActiveTypographySize: floatingLabelActiveTypographySizeClasses,
  nativeText: nativeTextClasses,
  nativePlaceholderTypographySize: nativePlaceholderTypographySizeClasses,
  nativeActiveWithoutTags: nativeActiveWithoutTagsClasses,
  nativeActiveWithoutTagsShiftSize: nativeActiveWithoutTagsShiftSizeClasses,
} as const;
