import {
  baseClasses,
  expandedClasses,
  collapsedClasses,
  headerClasses,
  headerCollapsedClasses,
  headerGapClasses,
  collapseButtonClasses,
  collapseIconClasses,
  collapseIconRotatedClasses,
  titleClasses,
  titleHiddenClasses,
  titleVisibleClasses,
  itemsContainerClasses,
  itemsContainerCollapsedClasses,
  footerClasses,
  footerCollapsedClasses,
  itemClasses,
  itemCollapsedClasses,
  actionButtonClasses,
  actionButtonCollapsedClasses,
  actionButtonExpandedClasses,
  actionButtonLabelClasses,
  actionButtonLabelHiddenClasses,
  actionButtonLabelVisibleClasses,
  linkDisabledClasses,
  linkNoUnderlineClasses,
  itemLabelClasses,
  itemLabelHiddenClasses,
  itemLabelVisibleClasses,
  baseMobileClasses,
} from "./base";

export {
  baseClasses,
  expandedClasses,
  collapsedClasses,
  headerClasses,
  headerCollapsedClasses,
  headerGapClasses,
  collapseButtonClasses,
  collapseIconClasses,
  collapseIconRotatedClasses,
  titleClasses,
  titleHiddenClasses,
  titleVisibleClasses,
  itemsContainerClasses,
  itemsContainerCollapsedClasses,
  footerClasses,
  footerCollapsedClasses,
  itemClasses,
  itemCollapsedClasses,
  actionButtonClasses,
  actionButtonCollapsedClasses,
  actionButtonExpandedClasses,
  actionButtonLabelClasses,
  actionButtonLabelHiddenClasses,
  actionButtonLabelVisibleClasses,
  linkDisabledClasses,
  linkNoUnderlineClasses,
  itemLabelClasses,
  itemLabelHiddenClasses,
  itemLabelVisibleClasses,
};

export const sidebarStyles = {
  root: baseClasses,
  mobileRoot: baseMobileClasses,
  rootExpanded: expandedClasses,
  rootCollapsed: collapsedClasses,
  header: headerClasses,
  headerCollapsed: headerCollapsedClasses,
  headerGap: headerGapClasses,
  collapseButton: collapseButtonClasses,
  collapseIcon: collapseIconClasses,
  collapseIconRotated: collapseIconRotatedClasses,
  title: titleClasses,
  titleHidden: titleHiddenClasses,
  titleVisible: titleVisibleClasses,
  itemsContainer: itemsContainerClasses,
  itemsContainerCollapsed: itemsContainerCollapsedClasses,
  footer: footerClasses,
  footerCollapsed: footerCollapsedClasses,
  item: itemClasses,
  itemCollapsed: itemCollapsedClasses,
  actionButton: actionButtonClasses,
  actionButtonCollapsed: actionButtonCollapsedClasses,
  actionButtonExpanded: actionButtonExpandedClasses,
  actionButtonLabel: actionButtonLabelClasses,
  actionButtonLabelHidden: actionButtonLabelHiddenClasses,
  actionButtonLabelVisible: actionButtonLabelVisibleClasses,
  linkDisabled: linkDisabledClasses,
  linkNoUnderline: linkNoUnderlineClasses,
  itemLabel: itemLabelClasses,
  itemLabelHidden: itemLabelHiddenClasses,
  itemLabelVisible: itemLabelVisibleClasses,
} as const;
