import {
  rootClasses,
  rootTopClasses,
  rootLeftClasses,
  avatarWrapperClasses,
  avatarLeftClasses,
  contentWrapperClasses,
  contentWrapperTopClasses,
  contentWrapperLeftClasses,
  contentClasses,
  titleClasses,
  subtitleClasses,
  labelsClasses,
  getLayoutClasses,
  getContentWrapperClasses,
  getAvatarLayoutClasses,
} from "./base";

import {
  sizeGapClasses,
  titleSizeClasses,
  subtitleSizeClasses,
  avatarSizeMap,
  labelSizeMap,
} from "./sizes";

export {
  rootClasses,
  rootTopClasses,
  rootLeftClasses,
  avatarWrapperClasses,
  avatarLeftClasses,
  contentWrapperClasses,
  contentWrapperTopClasses,
  contentWrapperLeftClasses,
  contentClasses,
  titleClasses,
  subtitleClasses,
  labelsClasses,
  getLayoutClasses,
  getContentWrapperClasses,
  getAvatarLayoutClasses,
  sizeGapClasses,
  titleSizeClasses,
  subtitleSizeClasses,
  avatarSizeMap,
  labelSizeMap,
};

export const userItemStyles = {
  root: rootClasses,
  rootTop: rootTopClasses,
  rootLeft: rootLeftClasses,
  avatarWrapper: avatarWrapperClasses,
  avatarLeft: avatarLeftClasses,
  contentWrapper: contentWrapperClasses,
  contentWrapperTop: contentWrapperTopClasses,
  contentWrapperLeft: contentWrapperLeftClasses,
  content: contentClasses,
  title: titleClasses,
  subtitle: subtitleClasses,
  labels: labelsClasses,
  sizeGap: sizeGapClasses,
  titleSize: titleSizeClasses,
  subtitleSize: subtitleSizeClasses,
  avatarSizeMap: avatarSizeMap,
  labelSizeMap: labelSizeMap,
  getLayout: getLayoutClasses,
  getContentWrapper: getContentWrapperClasses,
  getAvatarLayout: getAvatarLayoutClasses,
} as const;
