export {
  overlayClasses,
  contentWrapperClasses,
  contentLayoutClasses,
  contentBaseClasses,
  headerClasses,
  headerTitleWrapperClasses,
  headerTitleClasses,
  headerSubtitleClasses,
  headerActionSlotClasses,
  closeButtonClasses,
  separatorClasses,
  bodyClasses,
  footerClasses,
  headerBorderClasses,
  actionSlotBorderClasses,
  actionSlotWrapperClasses,
} from "./base";
export {
  modalWrapperClasses,
  modalContentClasses,
  fullScreenClasses,
  iceBoxWrapperClasses,
  iceBoxContentClasses,
  sizeClasses,
  closeButtonBaseClasses,
  closeButtonModalClasses,
  closeButtonIceBoxClasses,
  getWrapperClasses,
  getContentClasses,
  getCloseButtonClasses,
} from "./sizes";
export {
  overlayAnimationClasses,
  modalAnimationClasses,
  slideInAnimationClasses,
  getAnimationClasses,
} from "./animations";

import {
  overlayClasses,
  contentWrapperClasses,
  contentLayoutClasses,
  contentBaseClasses,
  headerClasses,
  headerTitleWrapperClasses,
  headerTitleClasses,
  headerSubtitleClasses,
  headerActionSlotClasses,
  closeButtonClasses,
  separatorClasses,
  bodyClasses,
  footerClasses,
  headerBorderClasses,
  actionSlotBorderClasses,
  actionSlotWrapperClasses,
  mobileCloseLineClasses,
  bodyPaddingClasses,
} from "./base";
import {
  modalWrapperClasses,
  modalContentClasses,
  fullScreenClasses,
  iceBoxWrapperClasses,
  iceBoxContentClasses,
  sizeClasses,
  getWrapperClasses,
  getContentClasses,
  getCloseButtonClasses,
} from "./sizes";
import { overlayAnimationClasses, getAnimationClasses } from "./animations";

export const modalStyles = {
  overlay: overlayClasses,
  contentWrapper: contentWrapperClasses,
  contentLayout: contentLayoutClasses,
  contentBase: contentBaseClasses,
  header: headerClasses,
  headerTitleWrapper: headerTitleWrapperClasses,
  headerTitle: headerTitleClasses,
  headerSubtitle: headerSubtitleClasses,
  headerActionSlot: headerActionSlotClasses,
  closeButton: closeButtonClasses,
  separator: separatorClasses,
  body: bodyClasses,
  bodyPadding: bodyPaddingClasses,
  footer: footerClasses,
  headerBorder: headerBorderClasses,
  actionSlotBorder: actionSlotBorderClasses,
  actionSlotWrapper: actionSlotWrapperClasses,
  wrapper: modalWrapperClasses,
  content: modalContentClasses,
  fullScreen: fullScreenClasses,
  iceBoxWrapper: iceBoxWrapperClasses,
  iceBoxContent: iceBoxContentClasses,
  size: sizeClasses,
  mobileCloseLine: mobileCloseLineClasses,
  getWrapper: getWrapperClasses,
  getContent: getContentClasses,
  getCloseButton: getCloseButtonClasses,
  getAnimation: getAnimationClasses,
  overlayAnimation: overlayAnimationClasses,
} as const;
