export {
  wrapperClasses,
  wrapperFillClasses,
  columnsContainerClasses,
  columnsContainerFillClasses,
  selectionPillClasses,
  columnClasses,
  columnClassesBase,
  columnClassesHeightFixed,
  columnClassesHeightFill,
  itemBaseClasses,
  itemHoverClasses,
  itemSelectedClasses,
  itemDisabledClasses,
  buttonsContainerClasses,
} from "./base";

import {
  wrapperClasses,
  wrapperFillClasses,
  columnsContainerClasses,
  columnsContainerFillClasses,
  selectionPillClasses,
  columnClasses,
  columnClassesBase,
  columnClassesHeightFixed,
  columnClassesHeightFill,
  itemBaseClasses,
  itemHoverClasses,
  itemSelectedClasses,
  itemDisabledClasses,
  buttonsContainerClasses,
} from "./base";

export const timeBarStyles = {
  wrapper: wrapperClasses,
  wrapperFill: wrapperFillClasses,
  columnsContainer: columnsContainerClasses,
  columnsContainerFill: columnsContainerFillClasses,
  selectionPill: selectionPillClasses,
  column: columnClasses,
  columnBase: columnClassesBase,
  columnHeightFixed: columnClassesHeightFixed,
  columnHeightFill: columnClassesHeightFill,
  itemBase: itemBaseClasses,
  itemHover: itemHoverClasses,
  itemSelected: itemSelectedClasses,
  itemDisabled: itemDisabledClasses,
  buttonsContainer: buttonsContainerClasses,
} as const;
