import { wrapperClasses } from "@/components/Field/styles";
import {
  dropZoneBaseClasses,
  dropZoneStateClasses,
  dropZoneActiveClasses,
  dropZoneDisabledClasses,
  dropZoneIconClasses,
  dropZoneIconDisabledClasses,
  dropZoneButtonClasses,
  dropZoneButtonDisabledClasses,
  dropZoneTextRowClasses,
  dropZoneTextSelectClasses,
  dropZoneTextSelectDisabledClasses,
  dropZoneTextDragClasses,
  dropZonePlaceholderClasses,
} from "./dropZone";
import {
  previewBaseClasses,
  previewStateClasses,
  previewErrorClasses,
  previewSizeClasses,
  previewInfoClasses,
  previewNameClasses,
  previewSizeTextClasses,
  previewActionsClasses,
  previewIconClasses,
  previewIconViewModeClasses,
  previewIconErrorClasses,
  previewIconSuccessClasses,
  previewLoadingClasses,
  previewIconLoadingClasses,
  previewListClasses,
} from "./filePreview";

export const inputFilesStyles = {
  wrapper: wrapperClasses,
  dropZone: {
    base: dropZoneBaseClasses,
    state: dropZoneStateClasses,
    active: dropZoneActiveClasses,
    disabled: dropZoneDisabledClasses,
    icon: dropZoneIconClasses,
    iconDisabled: dropZoneIconDisabledClasses,
    button: dropZoneButtonClasses,
    buttonDisabled: dropZoneButtonDisabledClasses,
    textRow: dropZoneTextRowClasses,
    textSelect: dropZoneTextSelectClasses,
    textSelectDisabled: dropZoneTextSelectDisabledClasses,
    textDrag: dropZoneTextDragClasses,
    placeholder: dropZonePlaceholderClasses,
  },
  preview: {
    list: previewListClasses,
    base: previewBaseClasses,
    state: previewStateClasses,
    error: previewErrorClasses,
    size: previewSizeClasses,
    info: previewInfoClasses,
    name: previewNameClasses,
    sizeText: previewSizeTextClasses,
    actions: previewActionsClasses,
    icon: previewIconClasses,
    iconViewMode: previewIconViewModeClasses,
    iconError: previewIconErrorClasses,
    iconSuccess: previewIconSuccessClasses,
    iconLoading: previewIconLoadingClasses,
    loading: previewLoadingClasses,
  },
} as const;
