import {
  countryEmptyClasses,
  countryFlagClasses,
  countryFlagFallbackClasses,
  countryListClasses,
  countryListItemClasses,
  countryListItemContentClasses,
  countryListItemNameClasses,
  countryListItemSuffixClasses,
  countryPopoverSurfaceClasses,
  countryScrollAreaClasses,
  countryScrollContainerClasses,
  countrySearchWrapperClasses,
  countryTriggerStateClasses,
  disabledClasses,
  fieldRowClasses,
  islandClasses,
  labelClasses,
  prefixClasses,
  separatorClasses,
  wrapperClasses,
} from "./base.ts";

import {
  iconSizeClasses,
  flagSizeClasses,
  inputPhoneWrapperSizeClasses,
  islandSizeClasses,
} from "./sizes.ts";

export {
  countryEmptyClasses,
  countryFlagClasses,
  countryFlagFallbackClasses,
  countryListClasses,
  countryListItemClasses,
  countryListItemContentClasses,
  countryListItemNameClasses,
  countryListItemSuffixClasses,
  countryPopoverSurfaceClasses,
  countryScrollAreaClasses,
  countryScrollContainerClasses,
  countrySearchWrapperClasses,
  countryTriggerStateClasses,
  disabledClasses,
  fieldRowClasses,
  islandClasses,
  labelClasses,
  prefixClasses,
  separatorClasses,
  wrapperClasses,
} from "./base.ts";

export {
  flagSizeClasses,
  iconSizeClasses,
  inputPhoneWrapperSizeClasses,
  islandSizeClasses,
  islandIconSizes,
} from "./sizes.ts";

export const inputPhoneStyles = {
  fieldRow: fieldRowClasses,
  wrapper: wrapperClasses,
  prefix: prefixClasses,
  label: labelClasses,
  separator: separatorClasses,
  disabled: disabledClasses,
  island: islandClasses,
  countryTriggerState: countryTriggerStateClasses,
  countryFlag: countryFlagClasses,
  countryFlagFallback: countryFlagFallbackClasses,
  countryPopoverSurface: countryPopoverSurfaceClasses,
  countrySearchWrapper: countrySearchWrapperClasses,
  countryScrollArea: countryScrollAreaClasses,
  countryScrollContainer: countryScrollContainerClasses,
  countryList: countryListClasses,
  countryListItem: countryListItemClasses,
  countryListItemSuffix: countryListItemSuffixClasses,
  countryListItemContent: countryListItemContentClasses,
  countryListItemName: countryListItemNameClasses,
  countryEmpty: countryEmptyClasses,
  islandSize: islandSizeClasses,
  wrapperSize: inputPhoneWrapperSizeClasses,
  iconSize: iconSizeClasses,
  flagSize: flagSizeClasses,
};
