import {
  textAreaBaseClasses,
  textAreaStateClasses,
  textAreaDisabledClasses,
  textAreaErrorClasses,
  textAreaNativeClasses,
  textAreaNativeBottomPaddingClasses,
  textAreaNativeWithLabelClasses,
  textAreaNativeTextBaseClasses,
  textAreaNativePlaceholderBaseClasses,
  textAreaNativeDisabledTextClasses,
  textAreaNativeDisabledClasses,
  textAreaWrapperInnerClasses,
  textAreaFieldShellClasses,
  textAreaCounterClasses,
  textAreaCounterDisabledClasses,
  textAreaClearButtonClasses,
  textAreaResizeHandleClasses,
  textAreaResizeVerticalClasses,
  textAreaResizeBothClasses,
  textAreaResizeIconClasses,
  requiredMarkClasses,
  textAreaLabelBaseClasses,
  textAreaLabelDisabledClasses,
  textAreaNativePlaceholderHiddenClasses,
  textAreaNativePlaceholderVisibleClasses,
} from "./base";
import {
  textAreaSizeClasses,
  textAreaSizeWithLabelClasses,
  textAreaFieldShellSizeClasses,
  textAreaLabelSizeClasses,
  textAreaLabelActiveSizeClasses,
  textAreaNativeTextSizeClasses,
  textAreaNativePlaceholderSizeClasses,
} from "./sizes";

export {
  textAreaBaseClasses,
  textAreaStateClasses,
  textAreaDisabledClasses,
  textAreaErrorClasses,
  textAreaNativeClasses,
  textAreaNativeBottomPaddingClasses,
  textAreaNativeWithLabelClasses,
  textAreaNativeTextBaseClasses,
  textAreaNativePlaceholderBaseClasses,
  textAreaNativeDisabledTextClasses,
  textAreaNativeDisabledClasses,
  textAreaWrapperInnerClasses,
  textAreaFieldShellClasses,
  textAreaCounterClasses,
  textAreaCounterDisabledClasses,
  textAreaClearButtonClasses,
  textAreaResizeHandleClasses,
  textAreaResizeVerticalClasses,
  textAreaResizeBothClasses,
  textAreaResizeIconClasses,
};
export {
  textAreaSizeClasses,
  textAreaSizeWithLabelClasses,
  textAreaFieldShellSizeClasses,
  textAreaLabelSizeClasses,
  textAreaLabelActiveSizeClasses,
  textAreaNativeTextSizeClasses,
  textAreaNativePlaceholderSizeClasses,
} from "./sizes";

export const textAreaStyles = {
  base: textAreaBaseClasses,
  state: textAreaStateClasses,
  disabled: textAreaDisabledClasses,
  error: textAreaErrorClasses,
  native: textAreaNativeClasses,
  nativeWithLabel: textAreaNativeWithLabelClasses,
  nativeBottomPadding: textAreaNativeBottomPaddingClasses,
  nativeTextBase: textAreaNativeTextBaseClasses,
  nativeTextSize: textAreaNativeTextSizeClasses,
  nativePlaceholderBase: textAreaNativePlaceholderBaseClasses,
  nativePlaceholderSize: textAreaNativePlaceholderSizeClasses,
  nativeDisabledText: textAreaNativeDisabledTextClasses,
  nativeDisabled: textAreaNativeDisabledClasses,
  size: textAreaSizeClasses,
  sizeWithLabel: textAreaSizeWithLabelClasses,
  fieldShell: textAreaFieldShellClasses,
  fieldShellSize: textAreaFieldShellSizeClasses,
  wrapperInner: textAreaWrapperInnerClasses,
  counter: textAreaCounterClasses,
  counterDisabled: textAreaCounterDisabledClasses,
  clearButton: textAreaClearButtonClasses,
  resizeHandle: textAreaResizeHandleClasses,
  resizeVertical: textAreaResizeVerticalClasses,
  resizeBoth: textAreaResizeBothClasses,
  resizeIcon: textAreaResizeIconClasses,
  requiredMark: requiredMarkClasses,
  label: textAreaLabelBaseClasses,
  labelActiveSize: textAreaLabelActiveSizeClasses,
  labelSize: textAreaLabelSizeClasses,
  labelDisabled: textAreaLabelDisabledClasses,
  nativePlaceholderHidden: textAreaNativePlaceholderHiddenClasses,
  nativePlaceholderVisible: textAreaNativePlaceholderVisibleClasses,
} as const;
